services:
  - type: web
    name: auto-rewriter
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 'rewriter:create_app()'
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.18
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
    disk:
      name: uploads
      mountPath: /opt/render/project/src/instance
      sizeGB: 1
